FROM node:lts-alpine AS build-stage
WORKDIR /home/ubuntu/GroceryApp/FE
COPY package.json package-lock.json ./
RUN npm install 
COPY . .
RUN sed -i 's|REACT_APP_API_URL=http://35.192.28.119:5000|REACT_APP_API_URL=http://13.235.74.27:5000|' .env 
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine AS production-stage
WORKDIR /var/www/grocery-app

# ✅ Corrected COPY path
COPY --from=build-stage /home/ubuntu/GroceryApp/FE/build/ /var/www/grocery-app

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

