FROM node:lts-alpine AS build-stage

# Set the working directory
WORKDIR /home/ubuntu/GroceryApp/FE

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install 

# Copy source code
COPY . .

# Update API URL in .env file
RUN sed -i 's|REACT_APP_API_URL=http://35.192.28.119:5000|REACT_APP_API_URL=http://43.204.215.101:5000|' .env

# Build the React app
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine AS production-stage

# Set working directory for Nginx
WORKDIR /var/www/grocery-app

# Copy build files from the previous stage
COPY --from=build-stage /home/ubuntu/GroceryApp/FE/build/ /var/www/grocery-app

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
